### ISSUE TITLE
Missing PKGBUILD

### ISSUE THREAD

**Issue by hvitoi** [markusressel/keyboard-backlight-daemon#46]
README mentions installation instructions using `yay -S keyboard-backlight-daemon-git`, however no such package is available at AUR nor PKGBUILD is provided as part of this repo. Is it something the developers still want to maintain as part of this project?

**Comment by markusressel** [comment]
Hey @hvitoi,

I wanted to create a package but didn't due to the complexity of maintaining it, and the probably incredibly small userbase. Also I am not yet 100% happy with the current implementation (even though I use it on my daily driver laptop).
Its this "not yet finished, but good enough to use it as is for now and not actually finish it" state :sweat_smile:

**Comment by hvitoi** [comment]
Well, I might be creating a PKGBUILD for my personal use. If you think that it interesting I can submit a PR with that (perhaps in a `contrib/` folder?). And modify README to instruct arch users to package it directly from PKGBUILD instead of installing from aur.

**Comment by markusressel** [comment]
Sure if that would help possible users, I will gladly accept a PR :+1:
